version: '3'

services:

  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - '5433:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}' ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: app
    tty: true
    env_file:
      - .env
    volumes:
      - .:/code
      - static:/code/static
      - media:/code/media
    ports:
      - "8001:8000"
    depends_on:
      db:
        condition: service_healthy
    command: bash -c "python manage.py migrate && python manage.py create_users && python manage.py collectstatic --no-input && python manage.py runserver 0.0.0.0:8000"

volumes:
  pg_data:
  static:
  media:


